# Deep Q-Learning

In [1]:
import gym
import numpy as np

In [159]:
env = gym.make('CartPole-v1')
eval_env = gym.make('CartPole-v1')

# Actions are discrete
dim_actions = np.array(env.action_space.n)

# States are continuous
dim_states = env.observation_space.shape[0]

print(dim_states)
print(dim_actions)


4
2


In [3]:
observation=env.reset()
observation

array([-0.00694907,  0.01014856,  0.04279254, -0.00519258], dtype=float32)

In [4]:
env.render()

True

In [5]:
import torch
import torch.nn as nn
import copy

In [6]:
class DeepQNetwork(nn.Module):
    
    def __init__(self, dim_states, dim_actions):
        super(DeepQNetwork, self).__init__()
        # MLP, fully connected layers, ReLU activations, linear ouput activation
        # dim_states -> 64 -> 64 -> dim_actions
        self.layers = nn.Sequential(
            nn.Linear(dim_states, 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, dim_actions)
        )

    def forward(self, input):
        q_values = self.layers(input)
        return q_values

In [7]:
deep_qnetwork = DeepQNetwork(4, 2)
target_deepq_network = copy.deepcopy(deep_qnetwork).eval()

In [8]:
target_deepq_network.load_state_dict(deep_qnetwork.state_dict())

<All keys matched successfully>

In [9]:
deep_qnetwork

DeepQNetwork(
  (layers): Sequential(
    (0): Linear(in_features=4, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=2, bias=True)
  )
)

In [14]:
observation

array([-0.00694907,  0.01014856,  0.04279254, -0.00519258], dtype=float32)

In [10]:
next_state = torch.from_numpy(observation).unsqueeze(dim=0).float()
next_state

tensor([[-0.0069,  0.0101,  0.0428, -0.0052]])

In [38]:
tensor1=next_state
tensor2=next_state

In [57]:
x=torch.empty(1)
x

tensor([1.0744e-38])

In [58]:
x[0]=tensor1
x

RuntimeError: expand(torch.FloatTensor{[4]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (1)

In [39]:
full=torch.cat([tensor1, tensor2], dim=0)

In [158]:
u[np.random.choice(10, size=3,replace=False)]

array([0., 0., 0.])

In [66]:
u[[1,2,3,10]]

array([0., 0., 0., 2.])

In [60]:
u=np.zeros(100)
u

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
u[10]=True

In [69]:
True==1

True

In [68]:
u

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
u[1]=tensor1
u

ValueError: only one element tensors can be converted to Python scalars

In [62]:
u

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
action=1

In [52]:
qsa=deep_qnetwork(full)
qsa

tensor([[ 0.0330, -0.0706],
        [ 0.0330, -0.0706]], grad_fn=<AddmmBackward>)

In [53]:
qsa=qsa[:,action]
qsa

tensor([-0.0706, -0.0706], grad_fn=<SelectBackward>)

In [54]:
qsa.shape

torch.Size([2])

In [27]:
import torch
import torch.nn as nn

import copy

import numpy as np

from replay_buffer import ReplayBuffer

from torch.optim import AdamW

import torch.nn.functional as F

In [42]:
optimizer = AdamW(deep_qnetwork.parameters(), lr=0.001)
optimizer

AdamW (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0.01
)

In [36]:
deep_qnetwork.zero_grad()

In [50]:
loss = F.mse_loss(qsa, qsa)
deep_qnetwork.zero_grad()
loss.backward()
optimizer.step()

In [22]:
qsa.argmax().item()

0

In [23]:
next_qsa_b = torch.max(qsa, dim=-1, keepdim=True)[0]
next_qsa_b

tensor([[-0.0545]], grad_fn=<MaxBackward0>)

In [10]:
target_deepq_network

DeepQNetwork(
  (layers): Sequential(
    (0): Linear(in_features=4, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=2, bias=True)
  )
)

In [19]:
target_b = 1+ False * 2
target_b

1